# .github/workflows/publish.yml

name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish
        required: true
        type: string

      dry_run:
        description: Skip publishing the packages
        required: true
        type: boolean
        default: false

      git_only:
        description: Only publish to github packages
        required: true
        type: boolean
        default: false

jobs:
  publish:
    name: Package and publish build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v7.0.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dotnet-version: '10.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Verify tag exists
        if: github.event_name == 'workflow_dispatch'
        run: |
          git fetch --tags
          git rev-parse "refs/tags/${{ inputs.tag }}" >/dev/null 2>&1 || {
            echo "Tag '${{ inputs.tag }}' does not exist."
            exit 1
          }

      - name: Extract version from tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ inputs.tag }}"
          else
            TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ./ImageStitcher.Tool/ImageStitcher.Tool.csproj

      - name: Build
        run: |
          dotnet build ./ImageStitcher.Tool/ImageStitcher.Tool.csproj \
            --configuration Release \
            --no-restore

      - name: Pack
        run: |
          dotnet pack ./ImageStitcher.Tool/ImageStitcher.Tool.csproj \
            --configuration Release \
            --no-restore \
            --no-build \
            /p:PackageVersion=${{ env.VERSION }} \
            --output ./nupkgs

      - name: Push to GitHub Packages
        if: ${{ inputs.dry_run != true }}
        run: |
          dotnet nuget push ./nupkgs/ImageStitcher.Tool*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: NuGet login
        uses: NuGet/login@v1.2.0
        id: login
        if: ${{ inputs.git_only != true }}
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet.org
        if: ${{ inputs.dry_run != true && inputs.git_only != true }}
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
